Modify add command to accept more parameters
CS2103AUG2016-W11-C4/main pull request #60
Opened 2016-10-08 10:35 UTC by Cherc

#46

2016-10-08 14:08 UTC, yamgent commented on .settings/org.eclipse.buildship.core.prefs
> -connection.gradle.user.home=null
Er the removal of this line is causing issues with our Gradle build...

Could you check whether your Eclipse is unintentionally removing this line?

2016-10-08 14:13 UTC, yamgent requested changes
Needs changes as pointed out in comments.

2016-10-08 14:13 UTC, yamgent commented on src/main/java/seedu/address/logic/parser/KeywordParser.java
> +    public HashMap<String, String> parseOne(String inputString){
Maybe can change to "parseForOneKeyword"

2016-10-08 14:13 UTC, yamgent commented on src/main/java/seedu/address/logic/parser/KeywordParser.java
> +    public HashMap<String, String> parseFree(String inputString){
Maybe can change to "parseKeywordsWithoutFixedOrder()"

2016-10-08 14:13 UTC, yamgent commented on .settings/org.eclipse.buildship.core.prefs
> -connection.gradle.user.home=null
Er the removal of this line is causing issues with our Gradle build...

Could you check whether your Eclipse is unintentionally removing this line?

2016-10-08 17:18 UTC, Cherc commented on .settings/org.eclipse.buildship.core.prefs
> -connection.gradle.user.home=null
restored the missing line

2016-10-08 17:23 UTC, Cherc commented on src/main/java/seedu/address/logic/parser/KeywordParser.java
> +    public HashMap<String, String> parseOne(String inputString){
Renamed. Though I had planned to replace the three with one parse method later on, when I'm more certain it works properly for all these cases.

2016-10-09 01:45 UTC, yamgent approved these changes

2016-10-09 01:46 UTC, merged